version: '3.8'

services:
  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: geth-node-$CONSENSUS
    entrypoint: /run_owner.sh
    command:
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --netrestrict="172.16.254.0/20"
    ports:
      - "8545:8545"

  geth-miner:
    hostname: geth-miner
    deploy:
      replicas: $MINERS
    env_file:
      - .env
    image: geth-node-$CONSENSUS
    entrypoint: /run_miner.sh
    command:
      --mine
      --miner.threads=1
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --netrestrict="172.16.254.0/20"
      
networks:
  default:
    # Fix: https://github.com/docker/compose-cli/issues/1856#issuecomment-870627818
    # external:
    name: bflnet
    external: true
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/20

