version: '3.8'

services:
  server:
    hostname: server
    image: bfl-node
    env_file:
      - .env_fl
    entrypoint: /root/run_server.sh
    deploy:
      mode: replicated
      # `replicas`: specifies the number of containers that should be running at any given time.
      replicas: $SERVERS
    environment:
      - IPFS_API=/dns/host.docker.internal/tcp/5001
      - CONTRACT=$CONTRACT
      - SCORING=$SCORING
      - MINERS=$MINERS
    volumes:
      # Use the following volume for a public validation dataset:
      - './datasets/$DATASET/$CLIENTS:/root/dataset'
      # - './datasets/$DATASET/$SERVERS:/root/dataset'
      - ../build/contracts/$ABI.json:/root/abi.json
    extra_hosts:
    - "host.docker.internal:host-gateway"

  client:
    hostname: client
    image: bfl-node
    env_file:
      - .env_fl
    entrypoint: /root/run_client.sh
    deploy:
      replicas: $CLIENTS
    environment:
      - IPFS_API=/dns/host.docker.internal/tcp/5001
      - CONTRACT=$CONTRACT
      - SCORING=$SCORING
      - MINERS=$MINERS
    volumes:
      - './datasets/$DATASET/$CLIENTS:/root/dataset'
      - ../build/contracts/$ABI.json:/root/abi.json
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  default:
    # Fix: https://github.com/docker/compose-cli/issues/1856#issuecomment-870627818
    # external:
    name: bflnet
    external: true
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/20
